services:
  stats-server:
    build: stat/stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: postgres-ewm-stats-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=ewm-stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  stats-db-init:
    image: postgres:16.1
    container_name: stats-db-init
    depends_on:
      stats-db:
        condition: service_healthy
    entrypoint:
      - bash
      - -c
      - |
        set -e
        psql postgresql://user:12345@stats-db:5432/ewm-stats -v ON_ERROR_STOP=1 <<-EOSQL
        CREATE TABLE IF NOT EXISTS hits (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        app varchar(1024) NOT NULL,
        uri varchar(2083) NOT NULL,
        ip varchar(31) NOT NULL,
        tstamp TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_hit PRIMARY KEY (id)
        );
        EOSQL

  ewm-service:
    build: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    environment:
      - CLIENT_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=main
      - SPRING_DATASOURCE_PASSWORD=main
